### Create configuration
POST http://localhost:8000/api/v1/create_configuration
Content-Type: application/json

{
    "guild_id": 1,
    "ticket_channel": 1,
    "questionnaire_channel": 1,
    "consideration_channel": 1,
    "moderator_roles": [1],
    "administrator_roles": [1]
}

### Search configuration
GET http://localhost:8000/api/v1/search_configuration?guild_id=1

### Update configuration
POST http://localhost:8000/api/v1/update_configuration
Content-Type: application/json

{
    "guild_id": 1,
    "moderator_roles": [2],
    "administrator_roles": [2]
}

### Delete configuration
POST http://localhost:8000/api/v1/delete_configuration
Content-Type: application/json

{
    "guild_id": 1
}
